apiVersion: customize.core.cnrm.cloud.google.com/v1beta1
kind: ControllerResource
metadata:
  name: cnrm-resource-stats-recorder
spec:
  containers:
    - name: recorder
      resources:
        limits:
          memory: 128Mi
